name: Sync README to index

on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Sync README.md to index.md
      run: |
        cp README.md index.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.md
        git commit -m 'Sync README.md to index.md'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
